### ISSUE TITLE
MDAnalysis issue"no Python.h"

### ISSUE THREAD

**Issue by xiaodiyu** [BradyAJohnston/MolecularNodes#216] opened 2023-04-30 17:24 UTC
Hi All, 

I was trying to update the most recent MolecularNodes. Everything went smoothly except the MDAnalysis installation and it showed "fatal error without Python.h"

I saw several suggestions previously but I was wondering if it was solved in this new version.

I'm using the Mac with M2.

Thanks,

Dee

**Comment by BradyAJohnston** [comment] 2023-05-01 02:29
This is still currently an issue of M1 / M2 mac users. The issue doesn't come from MolecularNodes, but rather that Blender can't compile python packages, so it requires pre-compiled binaries in order to install them successfully. Currently all of the installed python packages have pre-compiled binaries for M1 / M2, except MDAnalysis. They are aware of this, and are planning to add a compiled binary for the upcoming 2.5 release which should fix the issue https://github.com/MDAnalysis/mdanalysis/issues/4054. 

Until then it will remain problematic to install on ARM machines. The current best solution is to pre-compile the package yourself, and install that ([detailed in the installation instructions](https://bradyajohnston.github.io/MolecularNodes/installation.html#installing-biotite-mdanalysis)).

**Comment by BradyAJohnston** [comment] 2023-05-01 02:30
Duplicate of #108

**Closed by BradyAJohnston** 2023-05-01 02:30 UTC
