### ISSUE TITLE
non-english language issue in 2.3.0

### ISSUE THREAD

**Issue by Mangkun-Chen** [BradyAJohnston/MolecularNodes#146] opened 2023-01-29 01:56 UTC
![image](https://user-images.githubusercontent.com/108992267/215299976-588475d8-915a-435b-98b3-f3e5ddcad085.png)
![image](https://user-images.githubusercontent.com/108992267/215300013-62697a2d-0037-49a5-a6a0-e34fdd8c7664.png)

Hi Brady

I installed version 2.3.0. 
Problems still exist in the Chinese environment. Can you invite @ YaoYinYing to view this issue？I think he should be Chinese.

**Comment by Mangkun-Chen** [comment] 2023-01-29 01:59
@YaoYinYing

**Comment by YaoYinYing** [comment] 2023-01-29 04:38
@Mangkun-Chen did you ever restart Blender after switching language setting? This is actually essential for MN to apply a complete reloading.

**Comment by YaoYinYing** [comment] 2023-01-29 04:48
okay maybe that is the point. can you make the “新建数据(New Data)” checked and take another try?
<img width="286" alt="Snipaste_2023-01-29_12-45-14" src="https://user-images.githubusercontent.com/33014714/215305541-4a628431-7542-47d7-978b-10ba9400be26.png">

**Comment by Mangkun-Chen** [comment] 2023-01-29 05:07
![image](https://user-images.githubusercontent.com/108992267/215306096-0e701899-2a80-4383-9a1b-5a8bdf5da618.png)
@YaoYinYing I restart Blender. and open the “新建数据(New Data)”.  it is still reported error

**Comment by Mangkun-Chen** [comment] 2023-01-29 05:07
![image](https://user-images.githubusercontent.com/108992267/215306186-dd81f492-a329-4107-8c11-13c1591bf7e0.png)

**Comment by YaoYinYing** [comment] 2023-01-29 07:26
This looks wired. I cannot reproduce this error on either my macbook or retired windows laptop. Can you try to: 

1. change Language to Chinese,
2. keep this option of new data translation checked,
3. do a restart of Blender,
4. and finally load the PDB?

**Comment by Mangkun-Chen** [comment] 2023-01-30 01:42
@YaoYinYing it works now. 
不过很多插件开启“新建数据”会有bug，我一般关闭

**Comment by YaoYinYing** [comment] 2023-01-30 06:46
@Mangkun-Chen Thanks for reporting this issue. I have carefully read the official documents and submit a new PR #147 . It should be fixed soon.

**Comment by BradyAJohnston** [comment] 2023-01-30 06:57
Thanks for the bug report @Mangkun-Chen and for the fix @YaoYinYing, merged into master!

**Comment by Mangkun-Chen** [comment] 2023-01-31 01:27
Thank you！

**Closed** 2023-02-11 02:00 UTC
Labels: bug
