### ISSUE TITLE
Trouble loading trajectory

### ISSUE THREAD

**Issue by msinclair-py** [BradyAJohnston/MolecularNodes#583] opened 2024-08-28 14:37 UTC
**Describe the bug**
When I try to load my MD trajectory (in psf/dcd format) it crashes and the error indicates there are no coordinates in the MDA universe. If I separately load this traj into MDAnalysis myself there are no problems with the universe, as well as in other modeling software such as VMD. I have tried: loading it without custom selections, with custom selections, out of memory, and in memory and get different flavors of the same error. I am unfamiliar enough with blender that I don't think I will be able to debug this myself but I rooted around in the molecularnodes files and saw nothing that should cause this problem.

**Expected behavior**
Trajectory should load into blender.

**Error Codes**
Please include associated error codes that are shown in the python console when the error occurs.

```
Error: Python: Traceback (most recent call last):
  File "/home/msincla01/.config/blender/4.1/scripts/addons/molecularnodes/io/md.py", line 130, in execute
    mol, universe = load(
                    ^^^^^
  File "/home/msincla01/.config/blender/4.1/scripts/addons/molecularnodes/io/md.py", line 95, in load
    mol = session.show(
          ^^^^^^^^^^^^^
  File "/home/msincla01/.config/blender/4.1/scripts/addons/molecularnodes/io/parse/mda.py", line 548, in show
    mol_object = self._process_atomgroup(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msincla01/.config/blender/4.1/scripts/addons/molecularnodes/io/parse/mda.py", line 752, in _process_atomgroup
    vertices=ag_blender.positions,
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/msincla01/.config/blender/4.1/scripts/addons/molecularnodes/io/parse/mda.py", line 135, in positions
    return self.ag.positions * self.world_scale
           ^^^^^^^^^^^^^^^^^
  File "/Scr/msincla01/Software/blender-4.1.0-linux-x64/4.1/python/lib/python3.11/site-packages/MDAnalysis/core/groups.py", line 2538, in __getattr__
    raise NoDataError('This Universe has no coordinates')
MDAnalysis.exceptions.NoDataError: This Universe has no coordinates
```

**Desktop (please complete the following information):**
 - OS: Rocky 8
 - Hardware: Intel Xeon Gold 6134 / NVIDIA A6000
 - Blender Version: 4.1
- MolecularNodes Version: 4.1.3

**Additional context**
This trajectory has been processed to remove water molecules and the system wrapped with qwrap but I suspect this should not matter. I am happy to provide my input files but the trajectory is > 50Mb so it would need to be via Box/DropBox/etc.

**Comment by BradyAJohnston** [comment] 2024-08-29 00:31
Hmm I am unsure what might be the cause here. If you could try Upgrading Blender / Molecular Nodes to 4.2 (released a month ago) and see if it solves the problem, as there was a big re-write of the MD import code. Otherwise if you can share some example trajectories I can debug better that way.

**Comment by msinclair-py** [comment] 2024-09-03 16:07
Updating Blender did work although it reverted to this problem once and when I did a fresh install of MolecularNodes it appears to be working. In the interest of debugging however I am including a link to a psf/dcd file which was causing the issue in the above version of Blender/MolecularNodes: https://uofi.box.com/s/6y7mna5twi60nb4t8dg7ojwvwtlm6mfu. Let me know if you have issues accessing the files. I leave it up to you if you want to close this issue as it is working in the latest versions.

**Comment by BradyAJohnston** [comment] 2024-09-05 07:06
I'll have a download and maybe a play around with the files, but given this is now resolved in the newer versions I'll close this. Glad it's all working!

**Closed by BradyAJohnston** 2024-09-05 07:06 UTC
Labels: bug
