### ISSUE TITLE
v4.0.11 surface

### ISSUE THREAD

**Issue by Jojo109x** [BradyAJohnston/MolecularNodes#483] opened 2024-04-12 15:03 UTC
**Is your feature request related to a problem? Please describe.**
In [v4.0.11](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v4.0.11) a new way to depict surfaces was introduced. As far as I can tell the old method was removed. I really liked the old one because it did a better job at 'isolating' sidechains. With a bit of tweaking one was able to generate almost realistically looking high resolution electron density maps with the style (example settings: quality 4, scale radii 0.1, probe size 0.9, separation True). Although not particularly scientific, I loved the aesthetics of this. It was also quite unique compared to surface depications of pymol, chimera etc. 

**Describe the solution you'd like**
Could we please get the old surface style back as an optional alternative to the new one?

**Comment by Jojo109x** [comment] 2024-04-17 12:44
Thanks a lot! I will give this a try. 

In the meantime, I have found alternative parameters that produce similar results (high resolution electron density like appearance) with the new surface style. 

In case anyone is interested (Quality 4, Scale Radii 0.9, Probe Size 0.000, Separate True, Triangulate True, Relaxation steps 30)

**Comment by rbdavid** [comment] 2024-04-17 12:49
To avoid this issue in the future, I think it might be worthwhile to suggest a geometry node naming format where version numbers are included so that previous nodes are not lost. This runs the risk of creating bloat in the imported nodes but would enable back-compatibility and reproducibility of scientific visualizations. Worthy causes to strive for imo.  

For example, the geo node to draw a Cartoon style node is named `MN_style_cartoon`. I haven't dug through change logs to find when that node was last altered, so I'm gonna use placeholder text here. My suggestion for a new naming scheme is: the Cartoon style node to be renamed to `MN_style_cartoon_vX.X.X` to denote the node is "new as of version X.X.X". Then, when a new implementation of the Cartoon style node is pushed, that version is named `MN_style_cartoon_vY.Y.Y`. The old version of the node is moved from the `Geometry Node Editor's Add -> MolecularNodes` menu to the `Geometry Node Editor's Add -> Unassigned` menu tree to keep clutter down.

Also, dope image! I really need to start testing out the surface representations. Everyone seems to be heavily using those instead of cartoon reps.

**Comment by BradyAJohnston** [comment] 2024-09-05 08:17
I'm going to close this issue, as versioning of node groups is something that is going to be tackled upstream by Blender & GN (https://devtalk.blender.org/t/asset-linking-proposal/34127). It's something that there isn't a good solution to currently unfortunately. It just has to be treated with caution that node groups will go through large changes likely for major and minor versions (but not patch versions (4.2.X).

**Closed by BradyAJohnston** 2024-09-05 08:17 UTC
